spring:
  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521/pdborcl
#    username: risk
#    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 180000
      auto-commit: false
  liquibase:
    change-log: classpath:db/liquibase/master.xml
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://haasgz.hand-china.com:31306/test
#    username: root
#    password: handhand
  security:
    user:
      name: citi
      password: citi
  cache:
    caffeine:
      spec: maxmumSize=200,expireAfterAcess=600
  banner:
    image:
      location: banner.txt
  main:
    banner-mode: console
  thymeleaf:
    prefix: classpath:templates/prod/html
    # 开发时关闭缓存
    cache: false

server:
  port: 8090
mybatis-plus:
  mapper-locations: classpath:persistence/*.xml
  type-aliases-package: com.example.springbootdemo.domain
  configuration:
    local-cache-scope: session
logging:
  level:
    root: INFO
    org:
      hibernate: ERROR


